### ISSUE TITLE
let's add customisation for badge SVG's

### ISSUE THREAD

**Issue by revelt** [greenkeeperio/badges#16]
Hi!

The shields.io raised the bar allowing to customise the look of the badges, for example, make them flat and square by appending the attribute on the URL like:

```
https://img.shields.io/travis/codsen/ranges-sort.svg?style=flat-square
```

![ranges-sort](https://img.shields.io/travis/codsen/ranges-sort.svg?style=flat-square)

However, this does not work with **native Greenkeeper** badges:

```
https://badges.greenkeeper.io/codsen/ranges-sort.svg?style=flat-square
```

![greenkeeper](https://badges.greenkeeper.io/codsen/ranges-sort.svg?style=flat-square)

Notice the subtle difference between the two badges above.

Please implement the customisation to generate the flat and/or square SVG's upon request. Thank you.

**Comment by janl** [comment]
fixed in https://github.com/greenkeeperio/badges/pull/28
