### ISSUE TITLE
Styles not working

### ISSUE THREAD

**Issue by sonicdoe** [greenkeeperio/badges#40]
For example, for [`greenkeeperio/greenkeeper`](https://github.com/greenkeeperio/greenkeeper):

- `flat` (default): ![](https://badges.greenkeeper.io/greenkeeperio/greenkeeper.svg)
- `flat-square`: ![](https://badges.greenkeeper.io/greenkeeperio/greenkeeper.svg?style=flat-square)
- `plastic`: ![](https://badges.greenkeeper.io/greenkeeperio/greenkeeper.svg?style=plastic)

All styles work seem to work locally, it’s only badges.greenkeeper.io which always serves the same style. This might have something to do with caching since all three badges return the same ETag (`ef8933a07de557ea2af70751db30ba052ef8d6c17d58568e43724d0797e936dc-gzip`).

See also https://github.com/greenkeeperio/greenkeeper/issues/416.

**Comment by janl** [comment]
We’ve finally resolved this issue.
